# Generated by Django 6.0.4 on 2026-06-08 23:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimentacaoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENT', 'Entrada'), ('SAI', 'Saída'), ('AJP', 'Ajuste Positivo'), ('AJN', 'Ajuste Negativo'), ('DEV', 'Devolução')], db_index=True, max_length=3)),
                ('quantidade', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('observacoes', models.CharField(blank=True, max_length=200)),
                ('data_hora', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='catalogo.produto')),
            ],
            options={
                'verbose_name': 'Movimentação de Estoque',
                'verbose_name_plural': 'Movimentações de Estoque',
                'ordering': ['-data_hora'],
            },
        ),
    ]
