# Generated by Django 6.0.4 on 2026-06-08 23:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estoque', '0001_initial'),
        ('vendas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='referencia_venda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes', to='vendas.venda'),
        ),
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='responsavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes_realizadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='movimentacaoestoque',
            index=models.Index(fields=['produto', '-data_hora'], name='idx_movest_produto_data'),
        ),
    ]
