# Generated by Django 6.0.4 on 2026-06-10 00:07

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0008_peca_peso_gramas_alter_peca_status'),
        ('estoque', '0004_lote_movimentacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemlote',
            options={'ordering': ['produto__nome', 'peca__codigo'], 'verbose_name': 'Item de Lote', 'verbose_name_plural': 'Itens de Lote'},
        ),
        migrations.AlterUniqueTogether(
            name='itemlote',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='itemlote',
            name='peca',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='item_lote', to='catalogo.peca'),
        ),
        migrations.AddField(
            model_name='itemlote',
            name='peso_padrao',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Peso por peça (g)'),
        ),
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='peca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes', to='catalogo.peca'),
        ),
        migrations.AlterField(
            model_name='itemlote',
            name='produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='itens_lote', to='catalogo.produto'),
        ),
        migrations.AlterField(
            model_name='itemlote',
            name='quantidade',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
