# Generated by Django 6.0.4 on 2026-06-10 22:22

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0005_alter_itemlote_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemlote',
            name='custo_mao_de_obra',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
