# Generated by Django 6.0.4 on 2026-06-08 23:28

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Metal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('simbolo', models.CharField(help_text='Símbolo da API. Ex: XAU, XAG', max_length=10, unique=True)),
            ],
            options={
                'verbose_name': 'Metal',
                'verbose_name_plural': 'Metais',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_index=True, max_length=150)),
                ('descricao', models.TextField(blank=True)),
                ('peso_gramas', models.DecimalField(decimal_places=3, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('custo_mao_de_obra', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('margem_lucro', models.DecimalField(decimal_places=4, default=Decimal('0.3000'), help_text='Decimal. Ex: 0.30 = 30%', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))])),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Liga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('pureza', models.DecimalField(decimal_places=5, help_text='Fração pura do metal. Ex: 0.75000 para Ouro 18k', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00001')), django.core.validators.MaxValueValidator(Decimal('1.0'))])),
                ('metal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ligas', to='catalogo.metal')),
            ],
            options={
                'verbose_name': 'Liga',
                'verbose_name_plural': 'Ligas',
                'ordering': ['metal', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='CotacaoMetal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(db_index=True)),
                ('preco_por_grama', models.DecimalField(decimal_places=4, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('fonte', models.CharField(default='api', max_length=20)),
                ('metal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cotacoes', to='catalogo.metal')),
            ],
            options={
                'verbose_name': 'Cotação de Metal',
                'verbose_name_plural': 'Cotações de Metais',
                'ordering': ['-data', 'metal'],
            },
        ),
    ]
