# Generated by Django 6.0.4 on 2026-06-08 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='fornecedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos', to='vendas.fornecedor'),
        ),
        migrations.AddField(
            model_name='produto',
            name='liga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='catalogo.liga'),
        ),
        migrations.AlterUniqueTogether(
            name='cotacaometal',
            unique_together={('metal', 'data')},
        ),
    ]
