# Generated by Django 6.0.4 on 2026-06-08 23:59

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_tipoproduto_remove_produto_fornecedor_produto_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='margem_lucro',
        ),
        migrations.CreateModel(
            name='PrecoLiga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco_por_grama', models.DecimalField(decimal_places=4, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('vigente_desde', models.DateField(db_index=True)),
                ('definido_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='precos_definidos', to=settings.AUTH_USER_MODEL)),
                ('liga', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='precos', to='catalogo.liga')),
            ],
            options={
                'verbose_name': 'Preço de Liga',
                'verbose_name_plural': 'Preços de Liga',
                'ordering': ['liga', '-vigente_desde'],
                'unique_together': {('liga', 'vigente_desde')},
            },
        ),
    ]
