# Generated by Django 6.0.4 on 2026-06-09 00:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_remove_produto_margem_lucro_precoliga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='liga',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='catalogo.liga'),
        ),
    ]
