# Generated by Django 6.0.4 on 2026-06-09 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_lote_movimentacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Peca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, db_index=True, max_length=20, unique=True)),
                ('status', models.CharField(choices=[('DIS', 'Disponível'), ('RES', 'Reservada'), ('CON', 'Consignada'), ('VEN', 'Vendida')], db_index=True, default='DIS', max_length=3)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pecas', to='catalogo.produto')),
            ],
            options={
                'verbose_name': 'Peça',
                'verbose_name_plural': 'Peças',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='FotoPeca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='pecas/%Y/%m/')),
                ('principal', models.BooleanField(default=False)),
                ('ordem', models.PositiveSmallIntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('peca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='catalogo.peca')),
            ],
            options={
                'verbose_name': 'Foto de Peça',
                'verbose_name_plural': 'Fotos de Peças',
                'ordering': ['ordem', 'criado_em'],
            },
        ),
    ]
