# Generated by Django 6.0.4 on 2026-06-09 23:43

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0006_peca_fotopeca'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='preco_proprio',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Usado apenas para relógios (substitui o cálculo por peso/material).', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
