# Generated by Django 6.0.4 on 2026-06-10 00:07

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0007_produto_preco_proprio'),
    ]

    operations = [
        migrations.AddField(
            model_name='peca',
            name='peso_gramas',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Peso (g)'),
        ),
        migrations.AlterField(
            model_name='peca',
            name='status',
            field=models.CharField(choices=[('DIS', 'Disponível'), ('RES', 'Reservada'), ('CON', 'Consignada'), ('VEN', 'Vendida'), ('RET', 'Retirada')], db_index=True, default='DIS', max_length=3),
        ),
    ]
