# Generated by Django 6.0.4 on 2026-06-25 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0009_peca_custo_mao_de_obra_peca_preco_proprio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peca',
            name='preco_proprio',
        ),
    ]
