# Generated by Django 6.0.4 on 2026-06-25 06:06

from django.db import migrations, models


def consignada_para_disponivel(apps, schema_editor):
    Peca = apps.get_model('catalogo', 'Peca')
    Peca.objects.filter(status='CON').update(status='DIS')


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0010_remove_peca_preco_proprio'),
    ]

    operations = [
        migrations.RunPython(consignada_para_disponivel, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='peca',
            name='status',
            field=models.CharField(choices=[('DIS', 'Disponível'), ('RES', 'Reservada'), ('VEN', 'Vendida'), ('RET', 'Retirada')], db_index=True, default='DIS', max_length=3),
        ),
    ]
