# Generated by Django 6.0.4 on 2026-06-10 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0008_peca_peso_gramas_alter_peca_status'),
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemvenda',
            options={'ordering': ['venda'], 'verbose_name': 'Item de Venda', 'verbose_name_plural': 'Itens de Venda'},
        ),
        migrations.AddField(
            model_name='itemvenda',
            name='peca',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='itens_vendidos', to='catalogo.peca'),
        ),
        migrations.AlterUniqueTogether(
            name='itemvenda',
            unique_together={('venda', 'peca')},
        ),
        migrations.RemoveField(
            model_name='itemvenda',
            name='cotacao_referencia',
        ),
        migrations.RemoveField(
            model_name='itemvenda',
            name='produto',
        ),
        migrations.RemoveField(
            model_name='itemvenda',
            name='quantidade',
        ),
    ]
