# Generated by Django 6.0.4 on 2026-06-10 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0002_alter_itemvenda_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='atualizado_em',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='cpf_cnpj',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='email',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='endereco',
        ),
        migrations.AddField(
            model_name='cliente',
            name='observacao',
            field=models.TextField(blank=True),
        ),
    ]
