# Generated by Django 6.0.4 on 2026-06-25 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0003_cliente_simplificar'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedor',
            name='observacao',
            field=models.TextField(blank=True),
        ),
    ]
